 ## 取得陣列元素

如果我們想要取出一個或多個陣列的元素的話，我們就需要使用陣列內元素的索引去取得元素本身，還記得python原生的列表(list)嗎?陣列元素索引的使用方式與列表其實非常類似，只要在陣列後面以中括號**[   ]**並在裡面填入索引就可以了，差異在於陣列的維度是多維的，因此陣列元素的索引也是多維的。


In [1]:
import numpy as np

In [2]:
# 創建一個一維陣列
x = np.arange(6)
print(x)
# array([0, 1, 2, 3, 4, 5])

# 取出這個陣列的第三個元素
print(x[2])
# 2

# 取出這個陣列的倒數第二個元素
print(x[-2])
# 4

[0 1 2 3 4 5]
2
4


In [3]:
# 創建一個二維陣列
x = np.arange(6).reshape(2, 3)
print(x)
# [[0, 1, 2],
#  [3, 4, 5]])

# 取出第一個維度索引為0，第二個維度索引為2的元素
print(x[0, 2])
# 2

# 取出第一個維度索引為1，第二個維度索引為-1 (倒數第一)的元素
print(x[1, -1])
# 5

[[0 1 2]
 [3 4 5]]
2
5


- ### 取得陣列片段

同樣地，在陣列中要取得某一部份的元素我們同樣可以利用和列表(list)相似的辦法。

In [4]:
# 創建一個一維陣列
x = np.arange(6)
# array([0, 1, 2, 3, 4, 5])

In [5]:
# 取出這個陣列第二到第六個元素的片段(不含第六個元素)
print(x[1:5])
# [1, 2, 3, 4]

[1 2 3 4]


In [6]:
# 取出這個陣列從頭開始到第三個元素的片段(不含第三個元素)
print(x[:2])
# [0, 1]

[0 1]


In [7]:
# 取出這個陣列第二個到第六個元素的片段(不含第六個元素)，且每隔兩個值取一個元素
print(x[1:5:2])
# [1, 3]

[1 3]


In [8]:
# 創建一個二維陣列
x = np.arange(6).reshape(2, 3)
# [[0, 1, 2],
#  [3, 4, 5]])

In [9]:
# 取出這個陣列第一個維度索引為0，第二個維度從第一個到第三個元素的片段(不含第三個元素)
print(x[0, 0:2])
#  [0, 1]

[0 1]


In [10]:
# 取出這個陣列第一個維度的所有索引，第二個維度從第二個到最後一個元素的片段
print(x[:, 1:])
# [[1, 2],
#  [4, 5]]

[[1 2]
 [4 5]]


In [11]:
# 取出這個陣列第一個維度從頭到尾且每隔一個值取一個元素，第二個維度從頭到尾且每隔兩個值取一個元素的片段
print(x[::1, ::2])
# [[0, 2],
#  [3, 5]]

[[0 2]
 [3 5]]
